// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANL6AZceyIVocO-qgORGVMQ4TRm9wA6T0',
    appId: '1:523313958205:android:a3a4cd73a70a4128e54954',
    messagingSenderId: '523313958205',
    projectId: 'tryfirebase-2c389',
    databaseURL: 'https://tryfirebase-2c389.firebaseio.com',
    storageBucket: 'tryfirebase-2c389.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYSPwo4xXNaSDzCjXb3S6GKsb9kDsnDl4',
    appId: '1:523313958205:ios:624e0a608ee00e5fe54954',
    messagingSenderId: '523313958205',
    projectId: 'tryfirebase-2c389',
    databaseURL: 'https://tryfirebase-2c389.firebaseio.com',
    storageBucket: 'tryfirebase-2c389.appspot.com',
    iosClientId: '523313958205-a2ntp40gfb23tarsture0ptsn8ahd3v7.apps.googleusercontent.com',
    iosBundleId: 'com.pranayjangid.alemenoTask',
  );
}
